### ISSUE TITLE
E73-2G4M08S1C is not a good idea

### ISSUE THREAD

**Issue by Kabron287** [G-Pereira/greenmobi-bms#4]
It is BLE chip.
Windows does not work with BLE.
You will not be able to use Vesc/Ennoid tools.

You should use any Bluetooth SPP chip.

**Comment by G-Pereira** [comment]
Hi @Kabron287, thank you for your feedback.
This BLE module will be used to connect to mobile phones, hand held controllers (ex. joysticks) and other data logging/display devices. For example we can use this as well to monitor battery packs in storage units which discharge over time and need to be recharged. When this happens, an alert can be sent via a BLE gateway for large scale management of battery packs.

For the moment, to achieve the feature you suggest we are considering using the expansion header to connect a Bluetooth radio.

I'll keep this issue open until the block diagram is amended to state BLE instead of Bluetooth.

**Comment by Kabron287** [comment]
You Boss. You responce.

**Comment by G-Pereira** [comment]
Changes made. Thank you!
